---
- name: Update and upgrade apt packages
  hosts: all 
  tasks:
    - name: Update packages with apt
      when: ansible_pkg_mgr == 'apt'
      apt:
        update_cache: yes

    - name: Update packages with yum
      when: ansible_pkg_mgr == 'yum'
      yum:
        name: '*'
        state: latest

    - name: Upgrade packages with apt
      when: ansible_pkg_mgr == 'apt'
      apt:
        upgrade: dist

    - name: Upgrade packages with yum
      when: ansible_pkg_mgr == 'yum'
      yum:
        name: '*'
        state: latest
        exclude: kernel*
      register: apt_upgrade
    
    - name: send discord messagewith result
      uri:
        url: "{{ discord_webhook }}"
        method: POST
        body_format: json
        body: '{"content": "Vysledek {{ inventory_hostname }}: {{apt_upgrade.stdout}}"}'
        headers:
          Content-Type: application/json
        status_code: 204
      #when: apt_upgrade.stdout[:-1]|int > 80